FROM ruby:3.0.0-alpine


RUN apk add --no-cache --update build-base \
                                linux-headers \
                                git \
                                postgresql-dev \
                                nodejs \
                                yarn \
                                tzdata \
                                gcompat

RUN mkdir /app
WORKDIR /app

COPY Gemfile Gemfile.lock /app/
RUN gem install bundler:2.3.7
RUN bundle pack
RUN bundle install --path /gems --jobs `expr $(cat /proc/cpuinfo | grep -c "cpu cores") - 1` --retry 3
RUN gem install foreman

COPY . /app

EXPOSE 3000
CMD bundle exec rails s -p 3000

