version: '2'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  meilisearch:
    command: /bin/sh -c "./meilisearch --master-key=foo"
    image: getmeili/meilisearch:latest
    ports:
      - 7700:7700
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  memcached:
    image: memcached:latest
    ports:
      - 11211:11211
