require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/project_tags", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProjectTag. As you add validations to ProjectTag, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProjectTag.create! valid_attributes
      get project_tags_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      project_tag = ProjectTag.create! valid_attributes
      get project_tag_url(project_tag)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_project_tag_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      project_tag = ProjectTag.create! valid_attributes
      get edit_project_tag_url(project_tag)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProjectTag" do
        expect {
          post project_tags_url, params: { project_tag: valid_attributes }
        }.to change(ProjectTag, :count).by(1)
      end

      it "redirects to the created project_tag" do
        post project_tags_url, params: { project_tag: valid_attributes }
        expect(response).to redirect_to(project_tag_url(ProjectTag.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProjectTag" do
        expect {
          post project_tags_url, params: { project_tag: invalid_attributes }
        }.to change(ProjectTag, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post project_tags_url, params: { project_tag: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested project_tag" do
        project_tag = ProjectTag.create! valid_attributes
        patch project_tag_url(project_tag), params: { project_tag: new_attributes }
        project_tag.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the project_tag" do
        project_tag = ProjectTag.create! valid_attributes
        patch project_tag_url(project_tag), params: { project_tag: new_attributes }
        project_tag.reload
        expect(response).to redirect_to(project_tag_url(project_tag))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        project_tag = ProjectTag.create! valid_attributes
        patch project_tag_url(project_tag), params: { project_tag: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested project_tag" do
      project_tag = ProjectTag.create! valid_attributes
      expect {
        delete project_tag_url(project_tag)
      }.to change(ProjectTag, :count).by(-1)
    end

    it "redirects to the project_tags list" do
      project_tag = ProjectTag.create! valid_attributes
      delete project_tag_url(project_tag)
      expect(response).to redirect_to(project_tags_url)
    end
  end
end
